targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://dbc-baff2b7f-4402.cloud.databricks.com
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}
      state_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/state
    variables:
      app_name: multiagent-app-dev
      mlflow_experiment_id: "2041388166228723"
      subagents_config_path: "/app/python/source_code/.venv/lib/python3.11/site-packages/backend/domain/subagents.dev.json"
      default_request_persona: "manager"
      genie_space_id: "01f159f5d91419549020e3609add391c"
      store_manager_genie_space_id: ""
      executive_genie_space_id: ""
      supply_chain_genie_space_id: ""
      knowledge_assistant_endpoint_name: ""
      ai_search_endpoint_name: "knowledge-assistant-product-ep"
      message_bus_backend: structured_logging
      message_bus_topic: agent-lifecycle-events
      uc_audit_warehouse_id: "unused-for-structured-logging"
      uc_audit_catalog: "main"
      uc_audit_schema: "observability"
      uc_audit_table: agent_lifecycle_events
    resources:
      apps:
        multiagent-app:
          name: multiagent-app-dev
          usage_policy_id: "06846952-d579-4cd7-ab90-b86f0a1e3ed7"
          resources:
          - name: genie_space
            genie_space:
              name: Genie Space
              space_id: ${var.genie_space_id}
              permission: CAN_RUN